name: 'Get & Cache Dependencis' # Required
description: 'Get the dependencies (via npm) and cache them' # Required
inputs:
  caching:
    description: 'Whether to cache dependencies or not'
    required: false
    default: 'true'
outputs:
  used-cache:
    description: 'Whether the cache was used.'
    value: ${{ steps.install-deps.outputs.cache-output }}
env:
  CACHE_LOG: 'Did not use the cache...'
runs: # Required
  using: 'composite'
  steps:
    - name: Cache dependencies
      if: inputs.caching == 'true'
      id: cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      id: install-deps
      if: steps.cache.outputs.cache-hit != 'true' || inputs.caching != 'true'
      run: |
        npm ci
        echo "cache-output='{$CACHE_LOG}'" >> $GITHUB_OUTPUT
      shell: bash